version: '3.8'

services:
  js:
    image: node:18-alpine3.14
    user: node
    working_dir: /home/node/app
    ports:
      - 3000:3000
    volumes:
      - ./code:/home/node/app
    # entrypoint: /bin/sh
    command: node basics/web/server.js